// <auto-generated />

using MfcUfmt.Data;
using MfcUfmt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MfcUfmt.Migrations
{
    [DbContext(typeof(MfcUfmtContext))]
    partial class MfcUfmtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MfcUfmt.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<string>("NomeCurso");

                    b.Property<int>("TrabalhoId");

                    b.HasKey("Id");

                    b.HasIndex("TrabalhoId");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("MfcUfmt.Models.Trabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeTrabalho");

                    b.HasKey("Id");

                    b.ToTable("Trabalho");
                });

            modelBuilder.Entity("MfcUfmt.Models.Curso", b =>
                {
                    b.HasOne("MfcUfmt.Models.Trabalho", "Trabalho")
                        .WithMany()
                        .HasForeignKey("TrabalhoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
